### PR TITLE
Added an option in settings ini files to enable/disable vlan aware sanity test

### PR DESCRIPTION
**Pull request by rashidxf**

### CODE REVIEW

**Comment by rashidxf** [comment]
@gaelrehault kindly review the pull request

**Comment by gaelrehault** [comment]
@rashidxf  can you fix the conflict please ?

**Comment by rashidxf** [comment]
> @rashidxf can you fix the conflict please ?

@gaelrehault conflicts have been fixed. The pull request can now be merged.

**Comment by gaelrehault** [comment]
can you remove src/pilot/templates/ceph-osd-config.yaml.director ?

**Pull request merged**
