### PR TITLE
Adding sanity checks (File requirement + versions) based upon the profile

### PR DESCRIPTION
**Pull request by jproque-dell**

### CODE REVIEW

**Comment by gaelrehault** [comment]
Target version should be 3.5.x

**Comment by heydog15** [comment]
Why are we checking for 3.6?  Thought we were using 3.5.1?  Is this PR meant to be in the current release that is in 2 weeks because it is kind of late in the game

**Comment by jproque-dell** [comment]
> Why are we checking for 3.6? Thought we were using 3.5.1? Is this PR meant to be in the current release that is in 2 weeks because it is kind of late in the game

My fault! Will fix it. I confirm we use 3.5.1 version for first drop.

**Comment by jproque-dell** [comment]
Versions fixed. I have also reordered the checks so that the presence check is done before validating the profile.

**Review by heydog15 — APPROVED** [review]

**Pull request merged**
