### PR TITLE
[WIP] PowerFlex Gateway VM 

### PR DESCRIPTION
**Pull request by anusha-kandepu**
As part of this PR below mentioned changes are added
1) PowerFlex Gateway VM deployment scripts.
2) Integrate the deployment scripts with SAH.py and deployer.py.
3) Sanity checks for PowerFlex GW VM.
4) Added powerflex gw related fields in the properties file.

### CODE REVIEW

**Comment by anusha-kandepu** [comment]
Please hold on the review . I though of adding reviewers after complete testing .

**Comment by rajinir** [comment]
> Please hold on the review . I though of adding reviewers after complete testing .

No problem. We will wait

**Comment by jproque-dell** [comment]
Proposing to close this PR as Anusha will not be able to test it. I'll raise a PR with full automation + gateway deployment.

**Comment by rajinir** [comment]
> Proposing to close this PR as Anusha will not be able to test it. I'll raise a PR with full automation + gateway deployment.

Ok, sounds like a good idea. I'll close this review

**Pull request closed without merging**
