### PR TITLE
25g support: anaconda vlan support

### PR DESCRIPTION
**Pull request by cdearborn**
This patch allows the user to optionally specify an anaconda interface
that has a .vlanid suffix.

### CODE REVIEW

**Comment by gaelrehault** [comment]
Happy with this once @heydog15 verified this does not cause regression

**Comment by heydog15** [comment]
Successfully deployed with Chris's change without the vlan id added to the interface for anaconda in the .properties file.  Merging.

**Comment by heydog15** [comment]
Sorry, I don't have rights to merge.  Someone else will have to.

**Comment by rperryman** [comment]
Just finished and the anaconda is up and running all good.

**Pull request merged**
