### PR TITLE
Updates with configurations for 4 and 5 nic samples

### PR DESCRIPTION
**Pull request by rperryman**
Added the 5-NIC configuration that would support 25G.
Moved the 10G Configuration to a 4-NIC-10G no changes just file names. 
Left Old configuration in place untill everything is all settled down.

### CODE REVIEW

**Comment by cdearborn** [comment]
Looks good to me.

**Comment by heydog15** [comment]
Only thing I see is that the 4-nic workbook has stamp names on the logical layout page under the Vlan section.  Has R7-3048 on 2 rows.  Also the DNS for Floating net looks out of range unless routers are setup.

**Comment by jtwill98** [comment]
Lets address Kurt's eagle eye catches before merging.

**Comment by rperryman** [comment]
Pushed updated 4-Nic spreadsheet.

**Comment by heydog15** [comment]
Looks good.

**Pull request merged**
