### PR TITLE
Made the following changes in sanity script

### PR DESCRIPTION
**Pull request by zxa13**
OVS Offload port creation for SR-IOV in Sanity script
    Deleted the ceph-osd-config.yaml.director

### CODE REVIEW

**Comment by heydog15** [comment]
What is this PR for?  What is the Jira story/test case that this covers?

**Comment by zxa13** [comment]
> What is this PR for? What is the Jira story/test case that this covers?

The SRIOV port creation command is different in case of OVS Offload enabled. This fixes the issue.  The Jira story is CES-10493 (https://jira.dellemc-community.org/browse/CES-10493) which is now in Testing on the Jira board.

**Comment by heydog15** [comment]
Has this been tested?  Can you test this first with Offload disabled and make sure it works then enable it and test it again?

**Comment by zxa13** [comment]
> Has this been tested? Can you test this first with Offload disabled and make sure it works then enable it and test it again?

Yes I have tested this and the offload port is created only when SR-IOV offload is enabled in the sanity.ini file.

**Pull request closed without merging**
